services:
  - type: web
    name: sleep-telegram-bot
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.11.9
